include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
